const mongoose =require("mongoose");

const dataSchema = new mongoose.Schema({
    line1: [{type: String, required: true}],
    line2: [{type: String, required: true}],
    line3: [{type: String, required: true}],
    line4: [{type: String, required: true}],
    line5: [{type: String, required: true}],
    line6: [{type: String, required: true}],
    line7: [{type: String, required: true}],
    line8: [{type: String, required: true}],
    line9: [{type: String, required: true}],
    line10: [{type: String, required: true}],
    line11: [{type: String, required: true}],
    line12: [{type: String, required: true}],
    line13: [{type: String, required: true}],
    line14: [{type: String, required: true}],
    line15: [{type: String, required: true}],
    line16: [{type: String, required: true}],
    line17: [{type: String, required: true}],
    line18: [{type: String, required: true}],
    line19: [{type: String, required: true}],
    line20: [{type: String, required: true}],
    line21: [{type: String, required: true}],
    line22: [{type: String, required: true}],
    line23: [{type: String, required: true}],
    line24: [{type: String, required: true}],
    line25: [{type: String, required: true}],
    line26: [{type: String, required: true}],
    line27: [{type: String, required: true}],
    line28: [{type: String, required: true}],
    line29: [{type: String, required: true}],
    line30: [{type: String, required: true}],
    line31: [{type: String, required: true}],
    line32: [{type: String, required: true}],
    line33: [{type: String, required: true}],
    line34: [{type: String, required: true}],
    line35: [{type: String, required: true}],
    line36: [{type: String, required: true}],
    line37: [{type: String, required: true}],
})

module.exports = mongoose.model('data', dataSchema);